name: marvapp
description: A new Flutter project.
version: 1.0.0+7

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  animated_widgets: ^1.0.3
  firebase_database: ^10.3.6
  firebase_core_platform_interface: ^5.0.0
  firebase_core: ^2.24.0
  url_launcher_platform_interface: ^2.0.3
  plugin_platform_interface: ^2.0.0
  liquid_swipe: ^3.0.0
  change_app_package_name: ^1.1.0
  datetime_picker_formfield: ^2.0.0
  intl: ^0.18.1
  rename: ^3.0.1
  africa_schools: ^1.0.1
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.2.4
  animated_splash_screen: ^1.3.0 
  multiselect_formfield: ^0.1.7 
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  multiselect: ^0.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_logo.png"


  flutter_lints: ^1.0.0


     
flutter:
    uses-material-design: true

 
    assets:
      - assets/images/marv.png
      - assets/images/tutorhome.jpg
      - assets/images/tutorhome1.jpg
      - assets/icons/study.png
      - assets/icons/shield.png
      - assets/icons/class.png
      - assets/icons/excellence.png
      - assets/icons/mclass.png
      - assets/icons/reading.png
      - assets/icons/tutor.png
      - assets/icons/phone.png
      - assets/icons/whatsapp.png
      - assets/icons/mail.png
      - assets/icons/twitter.png
      - assets/icons/facebook.png
      - assets/images/applytutor.png
      - assets/images/getconnected.png
      - assets/images/gettutor.png
      - assets/images/project.png
      - assets/icons/practical.jpg
      
   

    fonts:
      - family: Pacifico
        fonts:
          - asset: fonts/Pacifico-Regular.ttf
          
      - family: JosefinSans
        fonts:
          - asset: fonts/JosefinSans-Bold.ttf
          - asset: fonts/JosefinSans-Medium.ttf
          - asset: fonts/JosefinSans-MediumItalic.ttf
      
      - family: Roboto
        fonts:
          - asset: fonts/Roboto-Bold.ttf
          
      - family: Comic Sans 
        fonts:
          - asset: fonts/ComicSansMS3.ttf

      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat-Regular.ttf

      - family: Source Sans Pro
        fonts:
          - asset: fonts/SourceSansPro-SemiBold.ttf

      
        
 